version: "3.8"

services:

  nginx:
    image: nginx:latest
    container_name: nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd

    depends_on:
      - app1
      - app2
      - app3
      - grafana

  app1:
    image: hashicorp/http-echo
    command: ["-text=app1"]
    
  app2:
    image: hashicorp/http-echo
    command: ["-text=app2"]

  app3:
    image: hashicorp/http-echo
    command: ["-text=app3"]

  grafana:
    image: grafana/grafana