server {

    listen 80;

    server_name app.localhost;

    location / {

        proxy_pass http://app_backend;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        limit_req zone=api_limit burst=20 nodelay;

    }
}