server {
    # NGINX listens for incoming HTTP requests on port 80.This port is exposed to the host and acts as the entry point for all external traffic coming into the system.
    listen 80;
    # Defines the domain/subdomain that this server block handles.
    # Any request sent to app.localhost will be processed here.

    server_name app.localhost;

    location / {
        # Forward incoming requests to the upstream load balancer called "app_backend". This upstream contains the three application replicas and distributes traffic between them.

        proxy_pass http://app_backend;
        # Pass the original Host header from the client request to the backend application. This ensures the backend knows which domain was used by the client.

        proxy_set_header Host $host;
        # Forward the real client IP address to the backend service.Without this, the backend would only see the IP of the NGINX container instead of the actual client.
        proxy_set_header X-Real-IP $remote_addr;
        # Apply rate limiting to protect the application from excessive requests or abuse. The limit_req zone
        # "api_limit" is defined in the main nginx.conf file.
        # burst=20 allows short bursts of extra requests while nodelay processes them immediately without queuing.

        limit_req zone=api_limit burst=20 nodelay;

    }
}