server {

    # NGINX listens for incoming HTTP requests on port 80
    # Requests to grafana.localhost will be handled by this server block
    listen 80;

    # Defines the subdomain used to access the Grafana dashboard
    server_name grafana.localhost;

    location / {

        # Forward incoming requests to the Grafana service running inside the Docker network on port 3000
        proxy_pass http://grafana:3000;

        # Pass original request information to the backend so Grafana knows the client host and IP address
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # Enable HTTP Basic Authentication to protect the monitoring dashboard from public access
        auth_basic "Restricted Access";

        # Path to the file containing allowed usernames and encrypted passwords for authentication
        auth_basic_user_file /etc/nginx/.htpasswd;

    }

}